### PR TITLE
fix: Use arrayBuffer instead of blob when memoizing responses

### PR DESCRIPTION
**Pull request by anakinj**
Resolves: React native compatibility 

### Description

The react native blob implementation is apparently a bit lacking. The memoization introduced in #437 is using some functions that do not exist in the react native blob.

Resulting in the following errors:
```
TypeError: _blob.text is not a function (it is undefined)
```

This change uses the `response.arrayBuffer()` combined with `TextEncoder`.

### Checklist

- [ ] If my changes require tests, I added them.
- [ ] If my changes affect backward compatibility, it has been discussed.
- [ ] If my changes require an update to the CONTRIBUTING.md guide, I updated it.

### How to QA [^1]

[^1]:
	Please use these labels when submitting a review:
	:question: #ask:&ensp;Ask a question.
	:bulb: #idea:&ensp;Suggest an idea.
	:warning: #issue:&ensp;Strongly suggest a change.
	:tada: #nice:&ensp;Share a compliment.

---

> [!NOTE]
> **Medium Risk**
> Changes the core `request()` deduplication/memoization path to buffer bodies as `ArrayBuffer`, which could affect response decoding and memory usage across all callers. Risk is moderate because it touches shared HTTP plumbing but is a localized behavioral swap.
> 
> **Overview**
> Fixes response memoization to be React Native compatible by buffering deduplicated responses using `response.arrayBuffer()` instead of `response.blob()`.
> 
> `memoizeResponse()` now reconstructs `text()`/`json()` via `TextDecoder`, exposes `arrayBuffer()`, and recreates `blob()` from the buffered bytes; `WriteClient.fetchForeignAsset()` is updated to build `File` objects from an `ArrayBuffer` rather than a `Blob`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 71c6c7eefea13e189fc275dea71b469672fe434f. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Review by lihbr — APPROVED** [review]
LGTM, thank you so much for taking the time to open a PR! 💙

**Review by angeloashmore — APPROVED** [review]
Looks good to me too! Thanks for the fix. 🙂
